import groovy.transform.NamedParam
import groovy.transform.NamedVariant

class Groovy25TestCase extends GroovyTestCase{

    @NamedVariant
    String bar(String s1, @NamedParam s2) {
        // Error reported on @NamedParam, but value attribute is automatically assigned
        "$s1 $s2"
    }

    void testGroovyFeatures() {
        println bar("foo", s2 : "bar")// Warning reported that bar(Map, String) doesn't exist, but it is generated by @NamedVariant
        assertTrue false
        assert false
    }

}
